### ISSUE TITLE
Unpinned version of node-sass allows bugs to creep in

### ISSUE THREAD

**Issue by patrickberkeley** [adopted-ember-addons/broccoli-sass-source-maps#18]
We're using `broccoli-sass-source-maps` via `ember-cli-sass`. Because the version of `broccoli-sass-source-maps` is [unpinned in `ember-cli-sass`](https://github.com/aexmachina/ember-cli-sass/blob/master/package.json#L17) and the version of `node-sass` is [unpinned in `broccoli-sass-source-maps`](https://github.com/aexmachina/broccoli-sass-source-maps/blob/master/package.json#L23). So even if we pin `ember-cli-sass` errors that go into `node-sass` can still surface (for example https://github.com/sass/node-sass/issues/1442).

I don't know if pinning to specific versions all the way down the chain is a great solution, but do you have any thoughts on how to better manage this?

**Comment by stavarotti** [comment]
We just ran into this issue and we're unable to build our apps.  Getting the following error:

``` bash
The Broccoli Plugin: [SassCompiler] failed with:
Error: Base-level rules cannot contain the parent-selector-referencing character '&'.
```

Given the following selector:

``` scss
.lt-ie9 & {
  ...
}
```

**Comment by csantero** [comment]
I was able to work around this in my app by pinning node-sass to "3.4.2".

**Comment by patrickberkeley** [comment]
@csantero yup that's what we did as well. I was just hoping to find a cleaner solution than that.

**Comment by stavarotti** [comment]
@csantero That's what we ended up doing as well.  Like @patrickberkeley stated, a little inconvenient to have to update 10s of apps.

**Comment by simonexmachina** [comment]
You can specify which version of node-sass to use with the [`nodeSass` option](https://github.com/aexmachina/broccoli-sass-source-maps#usage). 

Add the version that you want to use to _your_ package.json and then provide that version of the module using the `nodeSass` option:

``` js
var compileSass = require('broccoli-sass-source-maps');
var outputTree = compileSass(inputTrees, inputFile, outputFile, {
  nodeSass: require('node-sass'); // loads version in your package.json
});
```
