### ISSUE TITLE
Segfault when using Node 0.12

### ISSUE THREAD

**Issue by mike-north** [adopted-ember-addons/broccoli-sass-source-maps#19]
Due to a known [libsass](https://github.com/sass/libsass/issues/2017) issue, users of ember-cli-sass will currently get segfaults when using node.js 0.12

The fix for this is to NOT use node-sass ~3.5.0. While acknowledging that the root cause of the problem does not lie with this library, I suggest changing the constraint in your package.json to `~3.4.2` or something, to prevent users from having a bad experience.

**Comment by simonexmachina** [comment]
The solution to this issue is to [specify which version of node-sass to use](https://github.com/aexmachina/broccoli-sass-source-maps#choosing-the-version-of-node-sass) until the underlying issue is fixed.
