### ISSUE TITLE
incorect preffered dependency resolution

### ISSUE THREAD

**Issue by lifeart** [adopted-ember-addons/broccoli-sass-source-maps#30]
related issue: https://github.com/ember-cli/ember-cli/issues/9639#issuecomment-929625043

TLDR: dart-sass always put cwd as first step resolution path, and this is wrong behavour for broccoli build (we should have input tree as cwd)

workaround: replace cwd during sass build

**Comment by patricklx** [comment]
this should now work: https://github.com/adopted-ember-addons/broccoli-sass-source-maps/blob/master/index.js#L123

**Comment by lifeart** [comment]
Hi @patricklx! Nope, have tried it before (hardcoding), it seems problem in `dart-sass` https://github.com/ember-cli/ember-cli/issues/9639#issuecomment-929612363

**Comment by patricklx** [comment]
did you try with the new compile api?

**Comment by patricklx** [comment]
NodeImporter is now legacy code. if I'm correct, it should now use: https://github.com/sass/dart-sass/blob/main/lib/src/import_cache.dart#L70

this is implemented in the main branch to use the new api. Not released yet
