### ISSUE TITLE
Update mkdirp dependency

### ISSUE THREAD

**Issue by bianjp** [adopted-ember-addons/broccoli-sass-source-maps#4]
When I run `npm update`, I got this warning:

```
npm WARN unmet dependency /home/vanitas/media-helper/frontend/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/node-sass requires mkdirp@'^0.5.0' but will load
npm WARN unmet dependency /home/vanitas/media-helper/frontend/node_modules/ember-cli-sass/node_modules/broccoli-sass-source-maps/node_modules/mkdirp,
npm WARN unmet dependency which is version 0.3.5
```

Could you please update the mkdirp dependency version?

**Comment by simonexmachina** [comment]
This is probably just an npm issue. Just delete your node modules folder and run npm install

**Comment by bianjp** [comment]
Seems you're right.
But I think it's better to keep the dependencies latest. In addition, npm 3.x would maximally flaten dependencies, so different package could share the same sub dependency if they requires the same version.

**Comment by simonexmachina** [comment]
I'm aware of all that. PRs welcome!
